augmentation: True
image_size: [128,128,3] # as per Xception model requirement
batch_size: 32
include_top: False
epochs: 5
classes: 2
weights: imagenet
learning_rate: 0.001
momentum: 0.9 # for SGD optimizer
nesterov: True # for SGD optimizer
decay_steps: 1000 # for Adam optimizer
decay_rate: 0.9 # for Adam optimizer